# Site settings
title: Threat Hunting Research Blog
description: Sharing threat hunting analysis, techniques, and research
author: CertainlyP
email: your-email@example.com

# GitHub Pages settings
baseurl: ""
url: "https://certainlyp.github.io"

# Build settings
markdown: kramdown
theme: minima

# Syntax highlighting
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Permalink structure for blog posts
permalink: /:year/:month/:day/:title/

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Collections
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/

# Exclude files from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - "*.txt"
  - hello.py
