"""HTML report generator for TTP intelligence."""
from datetime import datetime
from typing import List, Dict, Any
import json


class ReportGenerator:
    """Generates HTML reports from analyzed TTP data."""

    def generate(self, analyzed_data: List[Dict[str, Any]], output_path: str):
        """Generate HTML report from analyzed content."""
        # Group by content type
        grouped = self._group_by_type(analyzed_data)

        html = self._build_html(grouped, analyzed_data)

        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(html)

        print(f"✓ Report generated: {output_path}")

    def _group_by_type(self, data: List[Dict]) -> Dict[str, List[Dict]]:
        """Group analyzed data by content type."""
        grouped = {}
        for item in data:
            content_type = item.get('content_type', 'unknown')
            if content_type not in grouped:
                grouped[content_type] = []
            grouped[content_type].append(item)
        return grouped

    def _build_html(self, grouped: Dict, all_data: List[Dict]) -> str:
        """Build complete HTML report."""
        date = datetime.now().strftime('%Y-%m-%d %H:%M')

        # Count stats
        total_sources = len(all_data)
        actionable = len([d for d in all_data if d.get('data')])

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TTP Intelligence Report - {date}</title>
    <style>
        {self._get_css()}
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>🔒 Daily Threat Intelligence Report</h1>
            <p class="meta">{date} | {total_sources} sources analyzed | {actionable} actionable items</p>
        </header>

        {self._build_summary(grouped)}

        {self._build_sections(grouped)}

        <footer>
            <p>Generated by TTP Monitoring System | Powered by Claude API</p>
        </footer>
    </div>
</body>
</html>"""
        return html

    def _get_css(self) -> str:
        """Return CSS styling for the report."""
        return """
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            background: #0d1117;
            color: #c9d1d9;
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Noto Sans', Helvetica, Arial, sans-serif;
            line-height: 1.6;
        }

        .container {
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
        }

        header {
            background: linear-gradient(135deg, #1f6feb 0%, #0d419d 100%);
            padding: 30px;
            border-radius: 12px;
            margin-bottom: 30px;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.3);
        }

        header h1 {
            font-size: 2.2em;
            margin-bottom: 10px;
            color: white;
        }

        .meta {
            color: rgba(255, 255, 255, 0.8);
            font-size: 0.95em;
        }

        .summary {
            background: #161b22;
            border: 1px solid #30363d;
            padding: 25px;
            border-radius: 8px;
            margin-bottom: 30px;
        }

        .summary h2 {
            color: #58a6ff;
            margin-bottom: 15px;
            font-size: 1.5em;
        }

        .stat-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 15px;
            margin-top: 20px;
        }

        .stat-card {
            background: #0d1117;
            border: 1px solid #30363d;
            padding: 15px;
            border-radius: 6px;
            border-left: 3px solid #58a6ff;
        }

        .stat-card .number {
            font-size: 2em;
            font-weight: bold;
            color: #58a6ff;
        }

        .stat-card .label {
            color: #8b949e;
            font-size: 0.9em;
        }

        .section {
            margin-bottom: 40px;
        }

        .section-header {
            background: #161b22;
            border-left: 4px solid #58a6ff;
            padding: 15px 20px;
            border-radius: 6px;
            margin-bottom: 20px;
        }

        .section-header h2 {
            color: #58a6ff;
            font-size: 1.8em;
        }

        .threat-card {
            background: #161b22;
            border: 1px solid #30363d;
            padding: 25px;
            margin-bottom: 20px;
            border-radius: 8px;
            border-left: 4px solid #f85149;
        }

        .threat-card.technique {
            border-left-color: #d29922;
        }

        .threat-card.tool {
            border-left-color: #a371f7;
        }

        .threat-card.actor {
            border-left-color: #ff7b72;
        }

        .threat-card h3 {
            color: #c9d1d9;
            font-size: 1.4em;
            margin-bottom: 15px;
        }

        .source-link {
            display: inline-block;
            color: #58a6ff;
            text-decoration: none;
            margin-bottom: 15px;
            font-size: 0.9em;
        }

        .source-link:hover {
            text-decoration: underline;
        }

        .subsection {
            margin: 20px 0;
        }

        .subsection h4 {
            color: #58a6ff;
            font-size: 1.1em;
            margin-bottom: 10px;
            border-bottom: 1px solid #30363d;
            padding-bottom: 5px;
        }

        .tag {
            display: inline-block;
            background: #1f6feb;
            color: white;
            padding: 4px 10px;
            border-radius: 4px;
            font-size: 0.85em;
            margin: 3px;
        }

        .tag.critical { background: #f85149; }
        .tag.high { background: #d29922; }
        .tag.medium { background: #58a6ff; }
        .tag.low { background: #8b949e; }

        .ioc {
            font-family: 'Courier New', monospace;
            background: #0d1117;
            padding: 12px;
            border-radius: 6px;
            border: 1px solid #30363d;
            overflow-x: auto;
        }

        .ioc code {
            color: #79c0ff;
            font-size: 0.9em;
        }

        .detection {
            background: #0d1117;
            padding: 15px;
            border-radius: 6px;
            border-left: 3px solid #3fb950;
            margin: 10px 0;
        }

        .detection pre {
            background: #010409;
            padding: 12px;
            border-radius: 4px;
            overflow-x: auto;
            color: #79c0ff;
            font-size: 0.9em;
        }

        ul, ol {
            margin-left: 20px;
            margin-top: 10px;
        }

        li {
            margin: 5px 0;
        }

        .key-finding {
            background: #0d1117;
            border-left: 3px solid #d29922;
            padding: 15px;
            border-radius: 6px;
            margin: 15px 0;
            font-style: italic;
        }

        footer {
            text-align: center;
            color: #8b949e;
            padding: 30px;
            border-top: 1px solid #30363d;
            margin-top: 40px;
        }

        .not-actionable {
            opacity: 0.6;
            font-size: 0.9em;
        }
        """

    def _build_summary(self, grouped: Dict) -> str:
        """Build executive summary section."""
        stats = []
        for content_type, items in grouped.items():
            if content_type != 'not_actionable':
                stats.append(f'<div class="stat-card"><div class="number">{len(items)}</div><div class="label">{content_type.replace("_", " ").title()}</div></div>')

        stats_html = ''.join(stats)

        return f"""
        <div class="summary">
            <h2>Executive Summary</h2>
            <div class="stat-grid">
                {stats_html}
            </div>
        </div>
        """

    def _build_sections(self, grouped: Dict) -> str:
        """Build all content sections."""
        sections = []

        # Define section order and styling
        section_config = {
            'ioc_based': ('🎯 IOC-Based Threats', 'threat-card'),
            'technique_research': ('🔬 Attack Techniques & Research', 'threat-card technique'),
            'tool_analysis': ('🛠️ Tool Analysis', 'threat-card tool'),
            'threat_actor_profile': ('👤 Threat Actor Intelligence', 'threat-card actor'),
            'vulnerability_analysis': ('🔓 Vulnerability Analysis', 'threat-card'),
            'detection_engineering': ('🔍 Detection Engineering', 'threat-card technique'),
        }

        for content_type, (title, card_class) in section_config.items():
            if content_type in grouped and grouped[content_type]:
                section_html = self._build_section(title, grouped[content_type], card_class, content_type)
                sections.append(section_html)

        # Add not actionable items at the end
        if 'not_actionable' in grouped and grouped['not_actionable']:
            section_html = self._build_not_actionable_section(grouped['not_actionable'])
            sections.append(section_html)

        return '\n'.join(sections)

    def _build_section(self, title: str, items: List[Dict], card_class: str, content_type: str) -> str:
        """Build a section for a specific content type."""
        cards = []
        for item in items:
            if item.get('data'):
                card_html = self._build_card(item, card_class, content_type)
                cards.append(card_html)

        cards_html = '\n'.join(cards)

        return f"""
        <div class="section">
            <div class="section-header">
                <h2>{title}</h2>
            </div>
            {cards_html}
        </div>
        """

    def _build_card(self, item: Dict, card_class: str, content_type: str) -> str:
        """Build a card for an individual item."""
        data = item.get('data', {})
        source_url = item.get('source_url', '')

        # Different rendering based on content type
        if content_type == 'ioc_based':
            return self._build_ioc_card(data, source_url, card_class)
        elif content_type == 'technique_research':
            return self._build_technique_card(data, source_url, card_class)
        elif content_type == 'tool_analysis':
            return self._build_tool_card(data, source_url, card_class)
        elif content_type == 'threat_actor_profile':
            return self._build_actor_card(data, source_url, card_class)
        elif content_type == 'vulnerability_analysis':
            return self._build_vuln_card(data, source_url, card_class)
        elif content_type == 'detection_engineering':
            return self._build_detection_card(data, source_url, card_class)
        else:
            return self._build_generic_card(data, source_url, card_class)

    def _build_ioc_card(self, data: Dict, source_url: str, card_class: str) -> str:
        """Build card for IOC-based intelligence."""
        threat_name = data.get('threat_name', 'Unknown Threat')
        iocs = data.get('iocs', {})
        technical = data.get('technical_details', {})
        detection = data.get('detection_queries', [])
        key_finding = data.get('key_findings', '')

        # Build IOC lists
        ioc_html = self._build_ioc_section(iocs)
        tech_html = self._build_technical_section(technical)
        detection_html = self._build_detection_section(detection)
        finding_html = f'<div class="key-finding"><strong>Key Finding:</strong> {key_finding}</div>' if key_finding else ''

        return f"""
        <div class="{card_class}">
            <h3>{threat_name}</h3>
            <a href="{source_url}" class="source-link" target="_blank">📎 Source →</a>
            {finding_html}
            {ioc_html}
            {tech_html}
            {detection_html}
        </div>
        """

    def _build_technique_card(self, data: Dict, source_url: str, card_class: str) -> str:
        """Build card for technique research."""
        name = data.get('technique_name', 'Unknown Technique')
        attack_vector = data.get('attack_vector', '')
        detection_gap = data.get('detection_gap', '')
        detection_ideas = data.get('detection_ideas', [])
        takeaway = data.get('key_takeaway', '')

        detection_list = '<ul>' + ''.join(f'<li>{idea}</li>' for idea in detection_ideas) + '</ul>' if detection_ideas else ''

        return f"""
        <div class="{card_class}">
            <h3>{name}</h3>
            <a href="{source_url}" class="source-link" target="_blank">📎 Source →</a>

            <div class="subsection">
                <h4>Attack Vector</h4>
                <p>{attack_vector}</p>
            </div>

            <div class="subsection">
                <h4>Detection Gap</h4>
                <p>{detection_gap}</p>
            </div>

            <div class="subsection">
                <h4>Detection Ideas</h4>
                {detection_list}
            </div>

            <div class="key-finding">
                <strong>Key Takeaway:</strong> {takeaway}
            </div>
        </div>
        """

    def _build_tool_card(self, data: Dict, source_url: str, card_class: str) -> str:
        """Build card for tool analysis."""
        name = data.get('tool_name', 'Unknown Tool')
        purpose = data.get('tool_purpose', '')
        detection_methods = data.get('detection_methods', [])
        takeaway = data.get('key_takeaway', '')

        detection_list = '<ul>' + ''.join(f'<li>{method}</li>' for method in detection_methods) + '</ul>' if detection_methods else ''

        return f"""
        <div class="{card_class}">
            <h3>{name}</h3>
            <a href="{source_url}" class="source-link" target="_blank">📎 Source →</a>

            <div class="subsection">
                <h4>Purpose</h4>
                <p>{purpose}</p>
            </div>

            <div class="subsection">
                <h4>Detection Methods</h4>
                {detection_list}
            </div>

            <div class="key-finding">
                <strong>Key Takeaway:</strong> {takeaway}
            </div>
        </div>
        """

    def _build_actor_card(self, data: Dict, source_url: str, card_class: str) -> str:
        """Build card for threat actor intelligence."""
        name = data.get('actor_name', 'Unknown Actor')
        ttp_changes = data.get('ttp_changes', '')
        watch_for = data.get('watch_for', '')

        return f"""
        <div class="{card_class}">
            <h3>{name}</h3>
            <a href="{source_url}" class="source-link" target="_blank">📎 Source →</a>

            <div class="subsection">
                <h4>TTP Changes</h4>
                <p>{ttp_changes}</p>
            </div>

            <div class="key-finding">
                <strong>Watch For:</strong> {watch_for}
            </div>
        </div>
        """

    def _build_vuln_card(self, data: Dict, source_url: str, card_class: str) -> str:
        """Build card for vulnerability analysis."""
        cve = data.get('cve_id', 'Unknown CVE')
        severity = data.get('severity', 'unknown')
        attack_vector = data.get('attack_vector', '')
        takeaway = data.get('key_takeaway', '')

        severity_tag = f'<span class="tag {severity}">{severity.upper()}</span>'

        return f"""
        <div class="{card_class}">
            <h3>{cve} {severity_tag}</h3>
            <a href="{source_url}" class="source-link" target="_blank">📎 Source →</a>

            <div class="subsection">
                <h4>Attack Vector</h4>
                <p>{attack_vector}</p>
            </div>

            <div class="key-finding">
                <strong>Key Takeaway:</strong> {takeaway}
            </div>
        </div>
        """

    def _build_detection_card(self, data: Dict, source_url: str, card_class: str) -> str:
        """Build card for detection engineering."""
        name = data.get('detection_name', 'Detection Rule')
        logic = data.get('detection_logic', '')
        takeaway = data.get('key_takeaway', '')

        return f"""
        <div class="{card_class}">
            <h3>{name}</h3>
            <a href="{source_url}" class="source-link" target="_blank">📎 Source →</a>

            <div class="detection">
                <pre>{logic}</pre>
            </div>

            <div class="key-finding">
                <strong>Key Takeaway:</strong> {takeaway}
            </div>
        </div>
        """

    def _build_generic_card(self, data: Dict, source_url: str, card_class: str) -> str:
        """Build generic card for other content."""
        return f"""
        <div class="{card_class}">
            <a href="{source_url}" class="source-link" target="_blank">📎 Source →</a>
            <pre>{json.dumps(data, indent=2)}</pre>
        </div>
        """

    def _build_not_actionable_section(self, items: List[Dict]) -> str:
        """Build section for non-actionable content."""
        item_list = []
        for item in items:
            summary = item.get('data', {}).get('summary', item.get('summary', 'No summary'))
            url = item.get('source_url', '')
            item_list.append(f'<li><a href="{url}" target="_blank">{summary}</a></li>')

        items_html = '<ul>' + ''.join(item_list) + '</ul>'

        return f"""
        <div class="section">
            <div class="section-header">
                <h2>ℹ️ Other Items (Not Actionable)</h2>
            </div>
            <div class="not-actionable">
                {items_html}
            </div>
        </div>
        """

    def _build_ioc_section(self, iocs: Dict) -> str:
        """Build IOC subsection."""
        if not iocs or not any(iocs.values()):
            return ''

        ioc_items = []
        for ioc_type, values in iocs.items():
            if values:
                if isinstance(values, dict):
                    for sub_type, sub_values in values.items():
                        if sub_values:
                            ioc_items.append(f'<strong>{sub_type.upper()}:</strong><br><code>{", ".join(sub_values)}</code>')
                elif isinstance(values, list):
                    ioc_items.append(f'<strong>{ioc_type.upper()}:</strong><br><code>{", ".join(values)}</code>')

        if not ioc_items:
            return ''

        ioc_html = '<br><br>'.join(ioc_items)

        return f"""
        <div class="subsection">
            <h4>Indicators of Compromise</h4>
            <div class="ioc">
                {ioc_html}
            </div>
        </div>
        """

    def _build_technical_section(self, technical: Dict) -> str:
        """Build technical details subsection."""
        if not technical or not any(technical.values()):
            return ''

        tech_items = []
        for key, value in technical.items():
            if value:
                label = key.replace('_', ' ').title()
                tech_items.append(f'<strong>{label}:</strong> {value}')

        if not tech_items:
            return ''

        tech_html = '<br><br>'.join(tech_items)

        return f"""
        <div class="subsection">
            <h4>Technical Details</h4>
            <div class="ioc">
                {tech_html}
            </div>
        </div>
        """

    def _build_detection_section(self, detection_queries: List[str]) -> str:
        """Build detection queries subsection."""
        if not detection_queries:
            return ''

        query_html = ''.join(f'<div class="detection"><pre>{query}</pre></div>' for query in detection_queries)

        return f"""
        <div class="subsection">
            <h4>Detection Queries</h4>
            {query_html}
        </div>
        """
